# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure container-socket-proxy path exists
  ansible.builtin.file:
    path: "{{ container_socket_proxy_base_path }}"
    state: directory
    mode: "0750"
    owner: "{{ container_socket_proxy_uid }}"
    group: "{{ container_socket_proxy_gid }}"

- name: Ensure container-socket-proxy support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ container_socket_proxy_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ container_socket_proxy_uid }}"
    group: "{{ container_socket_proxy_gid }}"
  with_items:
    - env
    - labels
  register: container_socket_proxy_support_files_result

- name: Ensure container-socket-proxy container image is pulled via community.docker.docker_image
  when: sysd_docker_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ container_socket_proxy_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ container_socket_proxy_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else container_socket_proxy_container_image_force_pull }}"
  register: result
  retries: "{{ container_retry }}"
  delay: "{{ container_retry_delay }}"
  until: result is not failed

- name: Ensure container-socket-proxy container image is pulled via ansible.builtin.command
  when: sysd_docker_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ sysd_docker_host_command }} pull {{ container_socket_proxy_container_image }}"
  register: result
  retries: "{{ container_retry }}"
  delay: "{{ container_retry_delay }}"
  until: result is not failed
  changed_when: "'Downloaded newer image' in result.stdout"

- name: Ensure container-socket-proxy container network is created via community.docker.docker_network
  when: sysd_docker_net_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ sysd_docker_ipv6_enabled }}"
    name: "{{ container_socket_proxy_container_network }}"
    driver: bridge
    driver_options: "{{ sysd_docker_net_driver_opts }}"
  until: result is not failed

- name: Ensure container-socket-proxy container network is created via ansible.builtin.command
  when: sysd_docker_net_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ sysd_docker_host_command }} network create
      {% if sysd_docker_ipv6_enabled %}--ipv6{% endif %}
      {{ sysd_docker_net_driver_opts_string }}
      {{ container_socket_proxy_container_network }}
  register: container_socket_proxy_network_creation_result
  changed_when: container_socket_proxy_network_creation_result.rc == 0
  failed_when: container_socket_proxy_network_creation_result.rc != 0 and 'already exists' not in container_socket_proxy_network_creation_result.stderr

- name: Ensure container-socket-proxy systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/container-socket-proxy.service.j2"
    dest: "{{ sysd_docker_service_path }}/{{ container_socket_proxy_identifier }}.service"
    mode: "0644"
  register: container_socket_proxy_systemd_service_result

- name: Determine whether container-socket-proxy needs a restart
  ansible.builtin.set_fact:
    container_socket_proxy_restart_necessary: >-
      {{
        container_socket_proxy_support_files_result.changed | default(false)
        or container_socket_proxy_systemd_service_result.changed | default(false)
        or container_socket_proxy_container_image_pull_result.changed | default(false)
      }}
